# Dockerfile 생성
FROM nvidia/cuda:12.3.0-runtime-ubuntu22.04

# 파일 복사
ADD . .

# 파이썬 최신 버전(3.9) 설치
RUN apt update && apt install -y python3.9

# pip 설치
RUN python3.9 -m pip install --upgrade pip

# torch 설치
RUN pip3 install torch

# transformers 설치
RUN pip3 install transformers